CREATE TABLE USUARIO(
ID INT NOT NULL,
NOME VARCHAR(40), 
NOME_USUARIO VARCHAR(40) NOT NULL,
TIPO VARCHAR(10) NOT NULL,
SENHA VARCHAR(30) NOT NULL,
EMAIL VARCHAR (40),

PRIMARY KEY (ID)

);


INSERT INTO USUARIO VALUES(3, 'LARISSA LEMOS', 'llemos', 'USR', '1234', 
'llemos@hotmail.com'); 

INSERT INTO USUARIO VALUES(2, 'HELBER', 'helber', 'USR', '1234', 
'HELBER@hotmail.com'); 

INSERT INTO USUARIO VALUES(1, 'JACKSON NASCIMENTO', 'jack', 'ADM', '87519023', 
'jacksonnascimento84@hotmail.com'); 

