CREATE TABLE CLIENTE(
ID INT IDENTITY(1,1) NOT NULL,
NOME VARCHAR(30) NOT NULL,
CPF VARCHAR(11) NOT NULL,

PRIMARY KEY(ID, CPF),

);

INSERT INTO CLIENTE VALUES ('JACKSON NASCIMENTO', '06412312428')

SELECT * FROM CLIENTE

ALTER TABLE CLIENTE
ADD EMAIL VARCHAR(40);



