CREATE TABLE COMPRAS (
COD_DA_COMPRA VARCHAR(100) NOT NULL,
DATA_DA_COMPRA DATETIME NOT NULL,
ID_CLIENTE INT NOT NULL 

PRIMARY KEY(COD_DA_COMPRA),
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID),


);


CREATE TABLE COMPRA_CLIENTE(
COD_DA_COMPRA VARCHAR(100) NOT NULL,
ID_CLIENTE INT NOT NULL,
ID_PRODUTO INT NOT NULL,


PRIMARY KEY(COD_DA_COMPRA),
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID),
FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID),
FOREIGN KEY (COD_DA_COMPRA) REFERENCES COMPRAS(COD_DA_COMPRA)
);



