CREATE TABLE COMPRA(
ID INT IDENTITY(1,1) NOT NULL,
ID_CLIENTE INT NOT NULL,
ID_PRODUTO INT NOT NULL,
CPF VARCHAR(11) NOT NULL,

PRIMARY KEY(ID),
FOREIGN KEY (ID_CLIENTE, CPF) REFERENCES CLIENTE(ID, CPF),
FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID)
);

ALTER TABLE COMPRA
ALTER COLUMN CPF VARCHAR(11)


SELECT * FROM CLIENTE
SELECT * FROM PRODUTO

INSERT INTO  COMPRA (ID_CLIENTE, ID_PRODUTO) VALUES(4, 2);

SELECT 
CL.ID   AS [ID DO CLIENTE],
CL.NOME AS [NOME DO CLIENTE],
CL.CPF	AS [CPF],
CL.EMAIL AS [EMAIL],
P.NOME   AS [NOME DO PRODUTO],
P.VALOR  AS [VALOR DO PRODUTO]

FROM COMPRA C INNER JOIN CLIENTE CL ON C.ID_CLIENTE = CL.ID INNER JOIN PRODUTO P ON C.ID_PRODUTO = P.ID

UPDATE CAIXA_EMPRESA SET VALOR_CAIXA += 2500 WHERE ID = 1

SELECT SUM(VALOR) FROM DESPESA

SELECT * FROM DESPESA

SELECT * FROM PRODUTO