CREATE TABLE ESTOQUE(
ID INT IDENTITY(1,1) NOT NULL,
ID_PRODUTO INT NOT NULL,
QUANTIDADE INT NOT NULL,

PRIMARY KEY(ID, ID_PRODUTO),
FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID) 

);

SELECT * FROM ESTOQUE

INSERT INTO ESTOQUE VALUES (1, 5)


SELECT E.ID, P.NOME, E.ID_PRODUTO, E.QUANTIDADE FROM PRODUTO P INNER JOIN ESTOQUE E ON P.ID = E.ID_PRODUTO


