CREATE TABLE LOG_OPERACOES(
ID INT IDENTITY(1,1) NOT NULL,
QUERY VARCHAR(200) NOT NULL,

PRIMARY KEY(ID),

);

use Sistema_Faturamento

SELECT * FROM LOG_OPERACOES
DELETE FROM LOG_OPERACOES WHERE QUERY LIKE '%SELECT%'
DELETE  FROM PRODUTO WHERE NOME = 'TESTE'

INSERT INTO LOG_OPERACOES VALUES ('DFDF ' )