SELECT 

	CLI.CPF AS [CPF DO CLIENTE],
	CLI.NOME AS [NOME DO CLIENTE],
	P.DESCRICAO    AS [DESCRIÇÃO DO PRODUTO],
    P.VALOR  AS [VALOR DO PRODUTO],
	C.DATA_DA_COMPRA  AS [DATA DA COMPRA],
	C.COD_DA_COMPRA   AS [CÓDIGO DA COMPRA]


FROM 

	COMPRAS C 
LEFT JOIN 
	COMPRA_CLIENTE CC 
	ON C.COD_DA_COMPRA = CC.COD_DA_COMPRA
LEFT JOIN
	CLIENTE CLI 
	ON CC.ID_CLIENTE = CLI.ID
LEFT JOIN
	PRODUTO P
	ON CC.ID_PRODUTO = P.ID


WHERE C.COD_DA_COMPRA= (SELECT TOP 1 COD_DA_COMPRA FROM COMPRAS WHERE ID_CLIENTE = CLI.ID ORDER BY DATA_DA_COMPRA DESC)


