
CREATE TABLE USUARIO(
ID INT IDENTITY(1,1) NOT NULL,
NOME VARCHAR(40), 
NOME_USUARIO VARCHAR(40) NOT NULL,
TIPO VARCHAR(10) NOT NULL,
SENHA VARCHAR(30) NOT NULL,
EMAIL VARCHAR (40),

PRIMARY KEY (ID)

);


SELECT * FROM USUARIO

INSERT INTO USUARIO VALUES('JACKSON NASCIMENTO', 'jack', 'ADM', '87519023', 
'jacksonnascimento84@hotmail.com'); 

INSERT INTO USUARIO VALUES('HELBER', 'helber', 'USR', '1234', 
'HELBER@hotmail.com'); 

INSERT INTO USUARIO VALUES('LARISSA LEMOS', 'llemos', 'USR', '1234', 
'llemos@hotmail.com'); 

