USE Sistema_Faturamento
SELECT 
CL.ID   AS [ID DO CLIENTE],
CL.NOME AS [NOME DO CLIENTE],
CL.CPF	AS [CPF],
CL.EMAIL AS [EMAIL],
P.NOME   AS [NOME DO PRODUTO],
P.VALOR  AS [VALOR DO PRODUTO],
C.COD_DA_COMPRA,
C.DATA_COMPRA

FROM COMPRA C INNER JOIN CLIENTE CL ON C.ID_CLIENTE = CL.ID INNER JOIN PRODUTO P ON C.ID_PRODUTO = P.ID


WHERE COD_DA_COMPRA = 
(SELECT TOP 1  COD_DA_COMPRA FROM     
WHERE  CL.ID = ID_CLIENTE 
ORDER BY DATA_COMPRA DESC )

